apiVersion: v2
name: express-botx
description: eXpress BotX API gateway
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/lavr/express-botx
sources:
  - https://github.com/lavr/express-botx
maintainers:
  - name: lavr
