apiVersion: v2
name: express-botx
description: eXpress BotX API gateway
type: application
version: 0.25.1
appVersion: "0.30.1"
home: https://github.com/lavr/express-botx
sources:
  - https://github.com/lavr/express-botx
maintainers:
  - name: lavr
