{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "express-botx.fullname" . }}
  labels:
    {{- include "express-botx.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    bots:
      {{- range $name, $bot := .Values.config.bots }}
      {{ $name }}:
        host: {{ $bot.host | quote }}
        id: {{ $bot.id | quote }}
        secret: {{ $bot.secret | quote }}
      {{- end }}
    {{- if .Values.config.chats }}
    chats:
      {{- range $alias, $uuid := .Values.config.chats }}
      {{ $alias }}: {{ $uuid | quote }}
      {{- end }}
    {{- end }}
    cache:
      {{- toYaml .Values.config.cache | nindent 6 }}
    server:
      {{- toYaml .Values.config.server | nindent 6 }}
{{- end }}
