{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "express-botx.fullname" . }}
  labels:
    {{- include "express-botx.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    bots:
      {{- range $name, $bot := .Values.config.bots }}
      {{ $name }}:
        host: {{ $bot.host | quote }}
        id: {{ $bot.id | quote }}
        {{- if $bot.token }}
        token: {{ $bot.token | quote }}
        {{- else }}
        secret: {{ $bot.secret | quote }}
        {{- end }}
      {{- end }}
    {{- if .Values.config.chats }}
    chats:
      {{- toYaml .Values.config.chats | nindent 6 }}
    {{- end }}
    cache:
      {{- toYaml .Values.config.cache | nindent 6 }}
    server:
      {{- toYaml .Values.config.server | nindent 6 }}
    {{- if .Values.config.queue }}
    queue:
      {{- toYaml .Values.config.queue | nindent 6 }}
    {{- end }}
    {{- if .Values.config.producer }}
    producer:
      {{- toYaml .Values.config.producer | nindent 6 }}
    {{- end }}
    {{- if .Values.config.worker }}
    worker:
      {{- toYaml .Values.config.worker | nindent 6 }}
    {{- end }}
    {{- if .Values.config.catalog }}
    catalog:
      {{- toYaml .Values.config.catalog | nindent 6 }}
    {{- end }}
{{- end }}
